### ISSUE TITLE
FindBy encrypted field

### ISSUE THREAD

**Issue by scolandrea** [TDMobility/DoctrineEncryptBundle#27]
Hi,

Im trying finyby using encrypted field but seem doesnt work this way.

How can i do it?,

Regards!

**Comment by westinpigott** [comment]
Only way to search an encrypted field is to have the field be Deterministic.  This means it shares a common salt with the rest of the records.   Then the encrypted value can be computed before hand and looked for.  It is case-sensative, and does not allow for string searches either.  While this is less secure, it is still salted and AES256 encryted (assuming you are using the supplied encryption provider)
